import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import i18n from "@shared/i18n";

const {
  mockGenerateTimestampedFilename,
  mockSaveTextFile,
  mockSaveBinaryFile,
  mockCreateMarkdownComponents,
  mockHtml2Canvas,
  mockCreateRoot,
  mockFlushSync,
  mockJsPDFConstructor,
  mockJsPDFAddPage,
  mockJsPDFAddImage,
  mockJsPDFDeletePage,
  mockJsPDFOutput,
} = vi.hoisted(() => ({
  mockGenerateTimestampedFilename: vi.fn(),
  mockSaveTextFile: vi.fn(),
  mockSaveBinaryFile: vi.fn(),
  mockCreateMarkdownComponents: vi.fn().mockReturnValue({}),
  mockHtml2Canvas: vi.fn(),
  mockCreateRoot: vi.fn(),
  mockFlushSync: vi.fn((cb: () => void) => cb()),
  mockJsPDFConstructor: vi.fn(),
  mockJsPDFAddPage: vi.fn(),
  mockJsPDFAddImage: vi.fn(),
  mockJsPDFDeletePage: vi.fn(),
  mockJsPDFOutput: vi.fn().mockReturnValue(new ArrayBuffer(4)),
}));

vi.mock("@shared/services/FileOperationsService", () => ({
  FileOperationsService: {
    FILTERS: {
      MARKDOWN: [{ name: "Markdown", extensions: ["md"] }],
      PDF: [{ name: "PDF", extensions: ["pdf"] }],
    },
    generateTimestampedFilename: mockGenerateTimestampedFilename,
    saveTextFile: mockSaveTextFile,
    saveBinaryFile: mockSaveBinaryFile,
  },
}));

vi.mock("../../../shared/components/Markdown/markdownComponents", () => ({
  createMarkdownComponents: mockCreateMarkdownComponents,
}));

vi.mock("html2canvas", () => ({
  default: mockHtml2Canvas,
}));

vi.mock("react-dom/client", () => ({
  createRoot: mockCreateRoot,
}));

vi.mock("react-dom", () => ({
  flushSync: mockFlushSync,
}));

vi.mock("jspdf", () => ({
  jsPDF: class MockJsPDF {
    internal = {
      pageSize: {
        getWidth: () => 595,
        getHeight: () => 842,
      },
    };

    constructor(options: unknown) {
      mockJsPDFConstructor(options);
    }

    addPage = (...args: unknown[]) => mockJsPDFAddPage(...args);
    addImage = (...args: unknown[]) => mockJsPDFAddImage(...args);
    deletePage = (...args: unknown[]) => mockJsPDFDeletePage(...args);
    output = (...args: unknown[]) => mockJsPDFOutput(...args);
  },
}));

import { MessageExportService } from "../MessageExportService";
import { collectWideDiagrams, computeSmartSliceHeight } from "../pdfPaginator";

describe("MessageExportService", () => {
  const originalRequestAnimationFrame = globalThis.requestAnimationFrame;

  beforeEach(() => {
    vi.clearAllMocks();
    mockCreateRoot.mockReturnValue({
      render: vi.fn(),
      unmount: vi.fn(),
    });
    mockHtml2Canvas.mockReset();
    mockHtml2Canvas.mockImplementation(async () => {
      const canvas = document.createElement("canvas");
      canvas.width = 1000;
      canvas.height = 2200;
      return canvas;
    });
    globalThis.requestAnimationFrame = ((cb: FrameRequestCallback) => {
      cb(0);
      return 1;
    }) as typeof requestAnimationFrame;
  });

  afterEach(() => {
    globalThis.requestAnimationFrame = originalRequestAnimationFrame;
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
  });

  it("exports markdown with default sanitized prefix", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.md");
    mockSaveTextFile.mockResolvedValueOnce({
      success: true,
      filename: "chat-message.md",
    });

    const result = await MessageExportService.exportMessageText({
      format: "markdown",
      content: "# hello",
      sessionId: "abcdef1234",
      messageId: "m-12345678",
    });

    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith(
      "chat-message-abcdef12-m-123456",
      "md",
    );
    expect(mockSaveTextFile).toHaveBeenCalledWith(
      "# hello",
      [{ name: "Markdown", extensions: ["md"] }],
      "chat-message.md",
    );
    expect(result).toEqual({ success: true, filename: "chat-message.md" });
  });

  it("returns markdown save errors", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.md");
    mockSaveTextFile.mockResolvedValueOnce({
      success: false,
      error: "cancelled",
    });

    const result = await MessageExportService.exportMessageText({
      format: "markdown",
      content: "text",
      filenamePrefix: "custom-prefix",
    });

    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith("custom-prefix", "md");
    expect(result).toEqual({ success: false, error: "cancelled" });
  });

  it("exports pdf using generated bytes", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    const pdfBytes = new Uint8Array([1, 2, 3]);
    const generatePdfSpy = vi
      .spyOn(MessageExportService as any, "generatePdfFromText")
      .mockResolvedValueOnce(pdfBytes);
    mockSaveBinaryFile.mockResolvedValueOnce({
      success: true,
      filename: "chat-message.pdf",
    });

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "render me",
      filenamePrefix: "custom-pdf",
    });

    expect(generatePdfSpy).toHaveBeenCalledWith("render me");
    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith("custom-pdf", "pdf");
    expect(mockSaveBinaryFile).toHaveBeenCalledWith(
      pdfBytes,
      [{ name: "PDF", extensions: ["pdf"] }],
      "chat-message.pdf",
    );
    expect(result).toEqual({ success: true, filename: "chat-message.pdf" });
  });

  it("returns pdf export error when generation fails", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    vi.spyOn(MessageExportService as any, "generatePdfFromText").mockRejectedValueOnce(
      new Error("pdf failed"),
    );

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "render me",
    });

    expect(mockSaveBinaryFile).not.toHaveBeenCalled();
    expect(result).toEqual({ success: false, error: "pdf failed" });
  });

  it("sanitizes empty session/message fragments to fallback message name", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.md");
    mockSaveTextFile.mockResolvedValueOnce({
      success: true,
      filename: "chat-message.md",
    });

    await MessageExportService.exportMessageText({
      format: "markdown",
      content: "hi",
      sessionId: "        ",
      messageId: "    ",
    });

    expect(mockGenerateTimestampedFilename).toHaveBeenCalledWith(
      "chat-message-message-message",
      "md",
    );
  });

  it("handles non-Error pdf exceptions with fallback message", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    vi.spyOn(MessageExportService as any, "generatePdfFromText").mockRejectedValueOnce("boom");

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "render me",
    });

    expect(result).toEqual({
      success: false,
      error: i18n.t("chat.messageActions.exportFailed"),
    });
  });

  it("returns saveBinaryFile errors for pdf export", async () => {
    mockGenerateTimestampedFilename.mockReturnValueOnce("chat-message.pdf");
    vi.spyOn(MessageExportService as any, "generatePdfFromText").mockResolvedValueOnce(
      new Uint8Array([9, 8, 7]),
    );
    mockSaveBinaryFile.mockResolvedValueOnce({
      success: false,
      error: "disk is read-only",
    });

    const result = await MessageExportService.exportMessageText({
      format: "pdf",
      content: "content",
    });

    expect(result).toEqual({ success: false, error: "disk is read-only" });
  });

  it("waitForExportRenderReady returns after pending mermaid disappears", async () => {
    vi.useFakeTimers();
    const nowSpy = vi.spyOn(Date, "now");
    nowSpy
      .mockReturnValueOnce(0)
      .mockReturnValueOnce(1)
      .mockReturnValueOnce(70)
      .mockReturnValue(120);

    const container = document.createElement("div");
    const pending = document.createElement("div");
    pending.setAttribute("data-mermaid-loading", "true");
    container.appendChild(pending);

    const waitPromise = (MessageExportService as any).waitForExportRenderReady(container);
    setTimeout(() => pending.remove(), 60);
    await vi.advanceTimersByTimeAsync(120);
    await waitPromise;
  });

  it("renderCanvasWithFallback retries without foreignObjectRendering after failure", async () => {
    const warningSpy = vi.spyOn(console, "warn").mockImplementation(() => {});
    const firstError = new Error("first render failed");
    const fallbackCanvas = document.createElement("canvas");
    fallbackCanvas.width = 400;
    fallbackCanvas.height = 300;

    const html2canvasMock = vi
      .fn()
      .mockRejectedValueOnce(firstError)
      .mockResolvedValueOnce(fallbackCanvas);
    const container = document.createElement("div");

    const canvas = await (MessageExportService as any).renderCanvasWithFallback(
      html2canvasMock,
      container,
    );

    expect(canvas).toBe(fallbackCanvas);
    expect(html2canvasMock).toHaveBeenNthCalledWith(
      1,
      container,
      expect.objectContaining({ foreignObjectRendering: true }),
    );
    expect(html2canvasMock).toHaveBeenNthCalledWith(
      2,
      container,
      expect.objectContaining({ foreignObjectRendering: false }),
    );
    expect(warningSpy).toHaveBeenCalledWith(
      "PDF capture with foreignObjectRendering=true failed:",
      firstError,
    );
  });

  it("renderCanvasWithFallback throws when fallback render is empty", async () => {
    const emptyCanvas = document.createElement("canvas");
    emptyCanvas.width = 0;
    emptyCanvas.height = 0;

    const html2canvasMock = vi
      .fn()
      .mockResolvedValueOnce(emptyCanvas)
      .mockResolvedValueOnce(emptyCanvas);

    await expect(
      (MessageExportService as any).renderCanvasWithFallback(
        html2canvasMock,
        document.createElement("div"),
      ),
    ).rejects.toThrow("PDF render failed (empty canvas)");
  });

  it("computeSmartSliceHeight chooses whitespace row near page boundary", () => {
    const width = 10;
    const highlightedWhitespaceRow = 388;
    const canvas = {
      width,
      height: 1000,
      getContext: vi.fn().mockReturnValue({
        getImageData: (_x: number, y: number, readWidth: number, readHeight: number) => {
          const data = new Uint8ClampedArray(readWidth * readHeight * 4);
          for (let row = 0; row < readHeight; row += 1) {
            const globalY = y + row;
            const pixel = globalY === highlightedWhitespaceRow ? 255 : 0;
            for (let col = 0; col < readWidth; col += 1) {
              const index = (row * readWidth + col) * 4;
              data[index] = pixel;
              data[index + 1] = pixel;
              data[index + 2] = pixel;
              data[index + 3] = 255;
            }
          }
          return { data };
        },
      }),
    } as unknown as HTMLCanvasElement;

    const sliceHeight = computeSmartSliceHeight(canvas, 0, 400);

    expect(sliceHeight).toBe(highlightedWhitespaceRow);
  });

  it("computeSmartSliceHeight falls back to fixed slice height when pixels are unreadable", () => {
    const canvas = {
      width: 600,
      height: 1500,
      getContext: vi.fn().mockReturnValue(null),
    } as unknown as HTMLCanvasElement;

    const sliceHeight = computeSmartSliceHeight(canvas, 0, 500);

    expect(sliceHeight).toBe(500);
  });

  it("generatePdfFromText renders markdown to multipage PDF and cleans up DOM nodes", async () => {
    const getContextSpy = vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue({
      fillStyle: "#fff",
      fillRect: vi.fn(),
      drawImage: vi.fn(),
    } as any);
    const dataUrlSpy = vi
      .spyOn(HTMLCanvasElement.prototype, "toDataURL")
      .mockReturnValue("data:image/jpeg;base64,abc");

    const bytes = await (MessageExportService as any).generatePdfFromText("# heading\n\ncontent");

    expect(mockCreateRoot).toHaveBeenCalledTimes(1);
    expect(mockFlushSync).toHaveBeenCalledTimes(1);
    expect(mockHtml2Canvas).toHaveBeenCalled();
    expect(mockJsPDFConstructor).toHaveBeenCalledWith({
      unit: "pt",
      format: "a4",
      orientation: "portrait",
    });
    expect(mockJsPDFAddImage).toHaveBeenCalled();
    expect(mockJsPDFAddPage).toHaveBeenCalled();
    expect(mockJsPDFOutput).toHaveBeenCalledWith("arraybuffer");
    expect(bytes).toBeInstanceOf(Uint8Array);
    expect(bytes.byteLength).toBe(4);
    expect(getContextSpy).toHaveBeenCalled();
    expect(dataUrlSpy).toHaveBeenCalled();
    expect(document.querySelector('[style*="2147483647"]')).toBeNull();
    expect(document.querySelector('[style*="2147483646"]')).toBeNull();
  });

  it("generatePdfFromText throws when slice canvas context is unavailable", async () => {
    const getContextSpy = vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue(null);

    await expect((MessageExportService as any).generatePdfFromText("content")).rejects.toThrow(
      "PDF render failed (no canvas context)",
    );

    expect(getContextSpy).toHaveBeenCalled();
  });

  it("generatePdfFromText is unavailable when document is missing", async () => {
    vi.stubGlobal("document", undefined);

    await expect((MessageExportService as any).generatePdfFromText("content")).rejects.toThrow(
      "PDF export is unavailable in this environment",
    );
  });

  it("generatePdfFromText accepts empty markdown content", async () => {
    const getContextSpy = vi.spyOn(HTMLCanvasElement.prototype, "getContext").mockReturnValue({
      fillStyle: "#fff",
      fillRect: vi.fn(),
      drawImage: vi.fn(),
    } as any);
    vi.spyOn(HTMLCanvasElement.prototype, "toDataURL").mockReturnValue(
      "data:image/jpeg;base64,abc",
    );

    await expect((MessageExportService as any).generatePdfFromText("")).resolves.toBeInstanceOf(
      Uint8Array,
    );
    expect(getContextSpy).toHaveBeenCalled();
  });

  it("collectWideDiagrams flags only wide-and-oversized diagrams and maps them to canvas y", () => {
    const rect = (top: number, bottom: number, width: number): DOMRect =>
      ({
        top,
        bottom,
        left: 0,
        right: width,
        width,
        height: bottom - top,
        x: 0,
        y: top,
        toJSON: () => ({}),
      }) as DOMRect;

    const container = document.createElement("div");
    Object.defineProperty(container, "clientWidth", { value: 794, configurable: true });
    container.getBoundingClientRect = () => rect(0, 1000, 794); // 1000 CSS px tall

    const addImg = (top: number, bottom: number, natW: number, natH: number, cssW: number) => {
      const wrap = document.createElement("div");
      wrap.setAttribute("data-mermaid-loading", "false");
      const img = document.createElement("img");
      Object.defineProperty(img, "naturalWidth", { value: natW, configurable: true });
      Object.defineProperty(img, "naturalHeight", { value: natH, configurable: true });
      img.style.width = `${cssW}px`;
      img.src = "data:image/png;base64,AAAA";
      img.getBoundingClientRect = () => rect(top, bottom, cssW);
      wrap.appendChild(img);
      container.appendChild(wrap);
    };

    addImg(100, 300, 2500, 1000, 1000); // wide (2.5) + oversized (1000 > 746) → divert
    addImg(400, 700, 500, 1000, 500); // tall (0.5) → keep inline
    addImg(800, 900, 800, 400, 400); // wide ratio but small (400 ≤ 746) → keep inline

    // canvas is 2x the container height → scaleY = 2.
    const result = collectWideDiagrams(container, {
      height: 2000,
    } as HTMLCanvasElement);

    expect(result).toHaveLength(1);
    expect(result[0].ratio).toBeCloseTo(2.5);
    expect(result[0].topPx).toBe(200);
    expect(result[0].bottomPx).toBe(600);
    expect(result[0].src).toContain("data:image/png");
  });
});
