/**
 * Build mode script (legacy name kept for compatibility).
 *
 * internal/public no longer rebrand product naming.
 * It only controls VITE_INTERNAL_BUILD for startup confirmation dialog.
 */

const fs = require("fs");
const path = require("path");

function parseArgs(argv) {
  return argv.reduce((acc, arg) => {
    if (!arg.startsWith("--")) return acc;

    const raw = arg.slice(2);
    const eqIndex = raw.indexOf("=");
    if (eqIndex === -1) {
      acc[raw] = true;
      return acc;
    }

    const key = raw.slice(0, eqIndex);
    const value = raw.slice(eqIndex + 1);
    acc[key] = value;
    return acc;
  }, {});
}

const args = parseArgs(process.argv.slice(2));
const target = args.target || "internal";
const checkOnly = Boolean(args.check);

if (!["internal", "public"].includes(target)) {
  console.error(`❌ Unknown target: ${target}`);
  console.error("   Valid targets: internal, public");
  process.exit(1);
}

const isInternalBuild = target === "internal";
const expectedValue = isInternalBuild ? "true" : "false";
const envPath = path.resolve(__dirname, "..", ".env");

const envContent = `# Auto-generated by mode script - DO NOT EDIT MANUALLY\n# Controls startup confirmation dialog in App.tsx\n# internal => show dialog, public => skip dialog\n\nVITE_INTERNAL_BUILD=${expectedValue}\n`;

if (checkOnly) {
  if (!fs.existsSync(envPath)) {
    console.error("❌ Missing .env file");
    process.exit(1);
  }

  const current = fs.readFileSync(envPath, "utf8");
  const regex = /^\s*VITE_INTERNAL_BUILD\s*=\s*(true|false)\s*$/m;
  const match = current.match(regex);
  if (!match || match[1] !== expectedValue) {
    console.error(`❌ Mode mismatch: expected VITE_INTERNAL_BUILD=${expectedValue}`);
    process.exit(1);
  }

  console.log(`✅ Mode check passed: ${target} (VITE_INTERNAL_BUILD=${expectedValue})`);
  process.exit(0);
}

fs.writeFileSync(envPath, envContent);
console.log(`\n🎛️  Build mode: ${target.toUpperCase()}`);
console.log(`   VITE_INTERNAL_BUILD=${expectedValue}`);
console.log("   Product naming stays fixed as Bodhi\n");
console.log(`✨ Mode updated: ${target}\n`);
